language: node_js

node_js:
  - 9

cache:
  directories:
    - node_modules

script:
  - cd client/ && npm install && npm install --only=dev --no-shrinkwrap && npm run test && CI=false TRAVIS_SECURE_ENV_VARS=true npm run build

branches:
  only:
  - master